---
deployment:
  tasks:
    - export ASSETSPATH=/home/siasmari/public_html/assets
    - export FTGURUPATH=/home/siasmari/public_html/foto_guru
    - export FTSISWAPATH=/home/siasmari/public_html/foto_siswa
    - /bin/rm -rf $ASSETSPATH
    - /bin/mkdir $ASSETSPATH
    - /bin/cp -R public/assets/. $ASSETSPATH
    - /bin/rm -rf $FTGURUPATH
    - /bin/mkdir $FTGURUPATH
    - /bin/cp -R public/foto_guru/. $FTGURUPATH
    - /bin/rm -rf $FTSISWAPATH
    - /bin/mkdir $FTSISWAPATH
    - /bin/cp -R public/foto_siswa/. $FTSISWAPATH
